spring:
  datasource:
    url: jdbc:mysql://${DB_url}:${DB_port}/ourblog?useSSL=false & allowPublicKeyRetrieval=true
    username: ${DB_name}
    password: ${DB_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.hibernate.sql: debug
jwt:
  header: Authorization
  secret: ${Secret_key}
  token-validity-in-seconds: 86400